name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Upgrade pip and install linters
      run: |
        python -m pip install --upgrade pip
        python -m pip install "black"
    - name: black compliance checks
      run: python -m black . --check

  pip:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: [ubuntu-latest]
            python-version: '3.9'
          # - os: [macos-latest]
          #   python-version: '3.11'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install compilers (linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install gfortran libopenmpi-dev

      - name: Install compilers (MacOS)
        if: runner.os == 'macOS'
        run: brew install cmake openmpi gcc

      - name: pip install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/PolyChord/PolyChordLite
          pip install anesthetic
          pip install git+https://github.com/adamormondroyd/flexknot

      - name: Test pip install
        run: |
          pip install .

